---
apiVersion: v1
kind: Service
metadata:
  name: LoginWebApp
  labels:
    app: LoginWebApp
spec:
  type: NodePort
  selector:
    app: LoginWebApp
  ports:
  - protocol: TCP
    port: 8080
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: LoginWebApp
spec:
  selector:
    matchLabels:
      app: LoginWebApp
  replicas: 1
  template:
    metadata:
      labels:
        app: LoginWebApp
    spec:
      containers:
      - name: LoginWebApp
        image: ravimore001/tomcat_image
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 1
